development:
  kannel_url: http://kannel_server:13013 # Kannel smsbox sendsms-port
  username: prayagupd # Kannel sendsms-user username
  password: 654~321 # Kannel sendsms-user password
  api_secret: testing # A secret key you will also configure in Kannel for extra security

## configure sms-service
group = sms-service
omit-empty = true
get-url = "http://www.badal-karkhana.com/sms/receive_message?api_secret=api_secret_you_set_in_kannel_rails_yml&from=%p&text=%a"
